### ISSUE TITLE
Delayed loading issue

### ISSUE THREAD

**Issue by Andrejs1979** [benjaminhoffman/gatsby-plugin-segment-js#28]
Page load events are not being sent after enabling delayed loading on Gatsby.
```
	{
			resolve: `gatsby-plugin-segment-js`,
			options: {
				prodKey: `***************`,
				trackPage: true,
				delayLoad: true,
				delayLoadTime: 1000
			}
		}
```

"gatsby": "^2.13.31"
 "gatsby-plugin-segment-js": "^3.1.0"

Thanks!

**Comment by benjaminhoffman** [comment]
super excited to announce, this issue is fixed!  hat tip to @TomPridham.  solved via https://github.com/benjaminhoffman/gatsby-plugin-segment-js/pull/30

issue is now closed.  please upgrade your version of this plugin to `v3.3.0` and definitely let us know if you are still experiencing any issues!

cc @Andrejs1979
